import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<header className="header">
					<div className="logo">
						<img src="./assets/logo.png" alt="Logo programista Wojciech" id="logo" />
						<h1>Blog programista Wojciech</h1>
					</div>
					<nav className="menu">
						<ul>
							<li>
								<Link href="/">Strona główna</Link>
							</li>
							<li>
								<Link href="/articles">Artykuły</Link>
							</li>
							<li>
								<Link href="/about">O mnie</Link>
							</li>
							<li>
								<Link href="/contact">Kontakt</Link>
							</li>
						</ul>
					</nav>
				</header>
				{children}
				<footer>
					<div>
						<p>&copy; 2024 Blog programista Wojciech. Wszelkie prawa zastrzeżone.</p>
					</div>
				</footer>
			</body>
		</html>
	)
}
